# -*- coding: utf-8 -*-
"""new_email_classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0Myk_3V-3k-J0sLIw_E1nl3pA5_R1Cr
"""

# Import Libraries


import pandas as pd
import nltk
import pickle

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


# Download NLTK Resources


nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')


# Load Dataset

df = pd.read_csv(
    "spam_ham_dataset.csv",
    encoding="latin-1"
)

print("Dataset Shape:", df.shape)


# Check Labels


print("\nLabel Mapping:")
print(df[['label', 'label_num']].drop_duplicates())

print("\nClass Distribution:")
print(df['label'].value_counts())


# Feature Engineering

df['num_chars'] = df['text'].apply(len)

df['num_words'] = df['text'].apply(
    lambda x: len(x.split())
)

print("\nAverage Statistics:")
print(
    df.groupby('label')[
        ['num_chars', 'num_words']
    ].mean()
)


# Text Preprocessing


ps = PorterStemmer()

stop_words = set(
    stopwords.words('english')
)

def transform_text(text):

    text = str(text).lower()

    words = nltk.word_tokenize(text)

    filtered_words = []

    for word in words:
        if word.isalnum():
            filtered_words.append(word)

    processed_words = []

    for word in filtered_words:
        if word not in stop_words:
            processed_words.append(word)

    stemmed_words = []

    for word in processed_words:
        stemmed_words.append(
            ps.stem(word)
        )

    return " ".join(stemmed_words)

# Apply preprocessing
df['transformed_text'] = df['text'].apply(
    transform_text
)


# TF-IDF Vectorization


tfidf = TfidfVectorizer(
    max_features=3000
)

X = tfidf.fit_transform(
    df['transformed_text']
)

y = df['label_num']


# Train-Test Split


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


# Train Model

model = LogisticRegression(
    max_iter=1000
)

model.fit(
    X_train,
    y_train
)


# Model Evaluation


y_pred = model.predict(X_test)

print("\n========== MODEL PERFORMANCE ==========")

print(
    "Accuracy :",
    accuracy_score(y_test, y_pred)
)

print(
    "Precision :",
    precision_score(y_test, y_pred)
)

print(
    "Recall :",
    recall_score(y_test, y_pred)
)

print(
    "F1 Score :",
    f1_score(y_test, y_pred)
)

print(
    "\nConfusion Matrix :\n",
    confusion_matrix(y_test, y_pred)
)

print(
    "\nClassification Report :\n",
    classification_report(y_test, y_pred)
)


# Save Model and Vectorizer


with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(tfidf, f)

print("\nModel saved as model.pkl")
print("Vectorizer saved as vectorizer.pkl")

import pickle
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

model = pickle.load(open("model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

ps = PorterStemmer()
stop_words = set(stopwords.words("english"))

def transform_text(text):
    text = text.lower()
    words = nltk.word_tokenize(text)

    words = [w for w in words if w.isalnum()]
    words = [w for w in words if w not in stop_words]
    words = [ps.stem(w) for w in words]

    return " ".join(words)

msgs = [
    "Good morning",
    "Are you coming to the office now?",
    "Congratulations! You won a free iPhone",
    "Claim your free reward now"
]

for msg in msgs:
    transformed = transform_text(msg)
    vector = vectorizer.transform([transformed])

    pred = model.predict(vector)[0]
    prob = model.predict_proba(vector)[0]

    print("\nMessage:", msg)
    print("Processed:", transformed)
    print("Prediction:", pred)
    print("Probabilities:", prob)